# Renvoient un type
à vérifier
"fonctionnels"


#adding_operator
.a_label.
align_directive
..an_instruction..
an_instruction
assembly_file
assembly_instructions
#byte_immediate_list
#...byte_immediate..
CarriageReturn_ERR
#cop0_reg
#cop2_reg
effective_instruction
end_directive
ent_directive
#.Identifier.
equ_directive
#expr..addop__expr..
#expression
#expr__logop__expr..logop__expr..
#expr__mulop__expr..mulop__expr..
#expr__shfop__expr
extern_directive
format_hint_mem
"format_label:j jal"
format_n:rfe syscall wait eret sync
format_od_rs
format_rd
format_rd_mem
format_rd_si16
format_rd_rs
format_rd_rs_rt
format_rd_rs_si16
format_rd_rs_ui16
format_rd_rt_rs
format_rd_rt_sham
format_rs
format_rs_label
format_rs_rt
format_rs_rt_label
format_rs_si16
format_rt_cop0r
format_rt_cop2r
format_rt_mem
format_ui20
global_directive
#signed_16_bit_immediate
#immediate
#integer_register
#label
labelable_directive
#logic_operator
macro_instruction
macro_label
macro_n
macro_rd_i32
macro_rd_label
macro_rd_rs
macro_rd_rt
macro_rs_label
memory_alloc_directive
memory_ascii_alloc
memory_asciiz_alloc
memory_byte_alloc
memory_lcomm_alloc
memory_comm_alloc
memory_space_alloc
memory_skip_alloc
memory_word_alloc
mips_instruction
#mul_div_operator
#primary
section_specification_directive
set_directive
#shift_operator
#term
unlabeled_directive
.unlabeled_instruction.
#unsigned_16_bit_immediate
#word_immediate_list
#...word_immediate..
